#!/bin/bash
# postinst script 
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#


# Set keyboard clt-alt-backspace to restart X.
#setxkbmap -option terminate:ctrl_alt_bksp

# Netrunner kde4rc.
if [ -e /etc/kde4rc ]
then
  cp /usr/share/netrunner/adjustments/kde/kde4rc /etc/kde4rc
fi

# wine-browsedrive.desktop replaced.
if [ -e /usr/share/applications/wine-browsedrive.desktop ]
then
  cp /usr/share/netrunner/adjustments/kde/wine-browsedrive.desktop /usr/share/applications/wine-browsedrive.desktop
fi

# Users default directories.
if [ -e /etc/xdg/user-dirs.defaults ]
then
  cp /usr/share/netrunner/adjustments/kde/user-dirs.defaults /etc/xdg/user-dirs.defaults
fi

# Netrunner version of startkde.
if [ -e /usr/bin/startkde ]
then
  cp /usr/share/netrunner/adjustments/kde/startkde /usr/bin/startkde
fi

# Add the gnome default applications list.
mkdir -p /etc/gnome
cp /usr/share/netrunner/adjustments/kde/defaults.list /etc/gnome/defaults.list


# amdcccle
# Use kdesudo for amd Radeon users
if [ -e /usr/share/fglrx/amdccclesu.desktop ]
then
  cp /usr/share/netrunner/adjustments/kde/amdccclesu.desktop /usr/share/fglrx/amdccclesu.desktop
fi

# Make gtk apps use KDE themeing when opened as the root user.

if [ ! -e /root/.gtkrc-2.0 ]
then
  cp /usr/share/netrunner-default-settings/dot-gtkrc-2.0-kde4 /root/.gtkrc-2.0
  cp /usr/share/netrunner-default-settings/dot-gtkrc-2.0-kde4 /root/.gtkrc-2.0-kde4
fi
if [ ! -e /root/.config/gtk-3.0/settings.ini ]
then
  mkdir -p /root/.config/gtk-3.0
  cp /usr/share/netrunner-default-settings/settings.ini /root/.config/gtk-3.0/settings.ini
fi

# Same for users

if [ ! -e /etc/skel/.gtkrc-2.0 ]
then
  cp /usr/share/netrunner-default-settings/dot-gtkrc-2.0-kde4 /etc/skel/.gtkrc-2.0
  cp /usr/share/netrunner-default-settings/dot-gtkrc-2.0-kde4 /etc/skel/.gtkrc-2.0-kde4
fi
if [ ! -e /etc/skel/.config/gtk-3.0/settings.ini ]
then
  mkdir -p /etc/skel/.config/gtk-3.0
  cp /usr/share/netrunner-default-settings/settings.ini /etc/skel/.config/gtk-3.0/settings.ini
fi

# Remove the activity icon
if [ -e /usr/share/kde4/apps/plasma-desktop/updates/addShowActivitiesManagerPlasmoid.js ]
then
  cp /usr/share/netrunner/adjustments/kde/addShowActivitiesManagerPlasmoid.js /usr/share/kde4/apps/plasma-desktop/updates/addShowActivitiesManagerPlasmoid.js
fi

# Hide gnome mplayer icon
if [ -e /usr/share/applications/gnome-mplayer.desktop ]
then
  cp /usr/share/netrunner/adjustments/kde/gnome-mplayer.desktop /usr/share/applications/gnome-mplayer.desktop
fi

# Remove illustration shortcut
if [ -e /usr/share/templates/Illustration.desktop ]
then
  rm /usr/share/templates/Illustration.desktop
fi

# Remove illustration template
if [ -e /usr/share/templates/.source/Illustration.odg ]
then
  rm /usr/share/templates/.source/Illustration.odg
fi

# Replace Presentation template
if [ -e /usr/share/templates/.source/Presentation.odp ]
then
  cp /usr/share/netrunner/adjustments/Presentation.odp /usr/share/templates/.source/Presentation.odp
fi

if [ -e /usr/share/kde4/services/plasma-containment-newspaper.desktop ]; then
sed -i "s@^X-KDE-ServiceTypes=Plasma/Applet,Plasma/Containment@#X-KDE-ServiceTypes=Plasma/Applet,Plasma/Containment@" /usr/share/kde4/services/plasma-containment-newspaper.desktop
fi

# transmission
if [ -e /usr/share/applications/transmission-qt.desktop ]
then
  sed -i "s@Exec=transmission-qt %F@Exec=transmission-qt %U@" /usr/share/applications/transmission-qt.desktop
fi

# Hide deprecated window decorations
function hide_deprecated {
    dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/lib/kde4/kwin_b2_config.so /usr/share/netrunner/hidden/kwin_b2_config.so
    dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/lib/kde4/kwin3_b2.so /usr/share/netrunner/hidden/kwin3_b2.so
    dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/lib/kde4/kwin3_laptop.so /usr/share/netrunner/hidden/kwin3_laptop.so
    dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/kde4/apps/kwin/decorations/kwin4_decoration_qml_plastik/metadata.desktop /usr/share/netrunner/hidden/plastik_metadata.desktop
    dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/lib/kde4/imports/org/kde/kwin/decorations/plastik/libplastikplugin.so /usr/share/netrunner/hidden/libplastikplugin.so
    dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/icons/oxy-yellow/index.theme /usr/share/netrunner/hidden/oxy-yellow_index.theme
    dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/icons/oxy-zion/index.theme /usr/share/netrunner/hidden/oxy-zion_index.theme
}

case "$1" in
    configure)
      hide_deprecated
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    triggered)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0


