#!/bin/bash

set -e

. /usr/share/debconf/confmodule

# unHide deprecated window decorations
function show_deprecated {
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/oxy-yellow_index.theme /usr/share/icons/oxy-yellow/index.theme 
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/oxy-zion_index.theme /usr/share/icons/oxy-zion/index.theme
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/desktoptoolbox_metadata.desktop /usr/share/plasma/packages/org.kde.desktoptoolbox/metadata.desktop
    # Hide cashew/hamburger QML UI
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/desktoptoolbox_ToolBoxRoot.qml /usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxRoot.qml
    # Show pulseaudio kcm (non working currently)
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/kcm_pulseaudio.desktop /usr/share/kservices5/kcm_pulseaudio.desktop
}

# Undo Diversions
function undo_diversions {
    # Firefox (instead of old adjust.py script)
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/lib/firefox/distribution/distribution.ini.orig /usr/lib/firefox/distribution/distribution.ini
    # kactivitymanager_file_item_linking_plugin
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/kservices5/kactivitymanagerd_fileitem_linking_plugin.desktop.orig /usr/share/kservices5/kactivitymanagerd_fileitem_linking_plugin.desktop
    # gmusicbrowser layout
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/gmusicbrowser/layouts/main.layout.orig /usr/share/gmusicbrowser/layouts/main.layout
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/gmusicbrowser/layouts/filterfun.layout.orig /usr/share/gmusicbrowser/layouts/filterfun.layout
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/gmusicbrowser/layouts/contrib.layout.orig /usr/share/gmusicbrowser/layouts/contrib.layout
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/gmusicbrowser/layouts/makeitlooklike.layout.orig /usr/share/gmusicbrowser/layouts/makeitlooklike.layout
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/gmusicbrowser/layouts/shimmer.layout.orig /usr/share/gmusicbrowser/layouts/shimmer.layout
    # gmusicbrowser main config file
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/gmusicbrowser/gmbrc.default.orig /usr/share/gmusicbrowser/gmbrc.default
}

case "$1" in
    remove|purge)
        #These files may have been created during installation
        rm -f /root/.gtkrc-2.0
        rm -f /root/.gtkrc-2.0-kde4
        rm -f /root/.config/gtk-3.0/settings.ini
        rm -f /etc/skel/.gtkrc-2.0
        rm -f /etc/skel/.gtkrc-2.0-kde4
        rm -f /etc/skel/.config/gtk-3.0/settings.ini
        show_deprecated
        undo_diversions
    ;;

    upgrade|abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
