#!/bin/bash

set -e

. /usr/share/debconf/confmodule

# unHide deprecated window decorations
function show_deprecated {
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/kwin_b2_config.so /usr/lib/kde4/kwin_b2_config.so 
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/kwin3_b2.so /usr/lib/kde4/kwin3_b2.so 
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/kwin3_laptop.so /usr/lib/kde4/kwin3_laptop.so 
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/plastik_metadata.desktop /usr/share/kde4/apps/kwin/decorations/kwin4_decoration_qml_plastik/metadata.desktop 
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/libplastikplugin.so /usr/lib/kde4/imports/org/kde/kwin/decorations/plastik/libplastikplugin.so 
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/oxy-yellow_index.theme /usr/share/icons/oxy-yellow/index.theme 
    dpkg-divert --package netrunner-default-settings --remove --rename --divert /usr/share/netrunner/hidden/oxy-zion_index.theme /usr/share/icons/oxy-zion/index.theme 
}

case "$1" in
    remove|purge)
        #These files may have been created during installation
        rm -f /etc/gnome/defaults.list
        rm -f /root/.gtkrc-2.0
        rm -f /root/.gtkrc-2.0-kde4
        rm -f /root/.config/gtk-3.0/settings.ini
        rm -f /etc/skel/.gtkrc-2.0
        rm -f /etc/skel/.gtkrc-2.0-kde4
        rm -f /etc/skel/.config/gtk-3.0/settings.ini
        show_deprecated
    ;;

    upgrade|abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
