#!/bin/bash

# Hide deprecated window decorations
function hide_deprecated {
    mkdir -p /usr/share/netrunner/hidden

    if [ -e /usr/lib/kde4/kwin_b2_config.so ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/kwin_b2_config.so /usr/lib/kde4/kwin_b2_config.so 
    fi
    if [ -e /usr/lib/kde4/kwin3_b2.so ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/kwin3_b2.so /usr/lib/kde4/kwin3_b2.so 
    fi
    if [ -e /usr/lib/kde4/kwin3_laptop.so ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/kwin3_laptop.so /usr/lib/kde4/kwin3_laptop.so 
    fi
    if [ -e /usr/share/kde4/apps/kwin/decorations/kwin4_decoration_qml_plastik/metadata.desktop ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/plastik_metadata.desktop /usr/share/kde4/apps/kwin/decorations/kwin4_decoration_qml_plastik/metadata.desktop
    fi
    if [ -e /usr/share/kde4/apps/kwin/decorations/kwin4_decoration_qml_plastik/contents/ui/main.qml ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/plastik_main.qml /usr/share/kde4/apps/kwin/decorations/kwin4_decoration_qml_plastik/contents/ui/main.qml
    fi
    if [ -e /usr/lib/kde4/imports/org/kde/kwin/decorations/plastik/libplastikplugin.so ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/libplastikplugin.so /usr/lib/kde4/imports/org/kde/kwin/decorations/plastik/libplastikplugin.so 
    fi
    if [ -e /usr/share/icons/oxy-yellow/index.theme  ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/oxy-yellow_index.theme /usr/share/icons/oxy-yellow/index.theme 
    fi
    if [ -e /usr/share/icons/oxy-zion/index.theme ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/oxy-zion_index.theme /usr/share/icons/oxy-zion/index.theme
    fi
    # Also hide pulseaudio.desktop here in autostart for fixing delayed startup. This should be removed with newer upstream versions
    if [ -e /etc/xdg/autostart/pulseaudio.desktop ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/share/netrunner/hidden/pulseaudio.desktop /etc/xdg/autostart/pulseaudio.desktop
    fi
    # Firefox (instead of old adjust.py script)
    if [ -e /usr/lib/firefox/distribution/distribution.ini ]; then
      dpkg-divert --package netrunner-default-settings --add --rename --divert /usr/lib/firefox/distribution/distribution.ini.orig /usr/lib/firefox/distribution/distribution.ini
    fi
    
}

hide_deprecated
